

### API SWAGGER

GET http://localhost:8000/api-docs

### API CREATE A NEW USER | JIKA EMAIL SUDAH TERDAFTAR SEBELUMNYA, MAKA PENDAFTARAN GAGAL

### KET : PASSWORD AKAN DI AMANKAN DALAM BENTUK BCRYPT 

POST http://localhost:8000/user/registration
Content-Type: application/json

{
    "fullname": "greiq",
    "email": "greiq@gmail.com",
    "password": "123456&Qz"
}


### API LOGIN, KET : MENDAPATKAN TOKEN BARU SETIAP KALI LOGIN LAGI
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "email": "greiqbaru@gmail.com",
    "password": "123456&Qz"
}

### API CREATE A NEW POST - 

### KET : JIKA INI PRIVATE API, KITA PERLU MEMASUKAN TOKEN YG TADI SUDAH KAMU DAPATKAN SAAT LOGIN, IBARAT TANDA PENGENAL

POST http://localhost:8000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsImZ1bGxuYW1lIjoiZ3JlaXEiLCJlbWFpbCI6ImdyZWlxYmFydUBnbWFpbC5jb20iLCJpYXQiOjE2NjA1NTc2NzAsImV4cCI6MTY2MDY0NDA3MH0.ISUqlaOzPNuowGc8hgyyOHBYYryigVLWrU7ozIHibts

{
    "title": "Pantai",
    "image": "https://salsawisata.b-cdn.net/wp-content/uploads/2021/11/Pantai-Gatra.jpg",
    "body": "Pantai Gatra merupakan salah satu pantai terindah di Indonesia"
}

### API GET ALL USER | PUBLIC API (EXAMPLE)

GET http://localhost:8000/users

### API GET ALL POST| PUBLIC API

GET http://localhost:8000/posts

### API GET POST WITH PAGINATION

GET http://localhost:8000/posts?pageNumber=1

### API GET POST SORT | PUBLIC API

GET http://localhost:8000/posts?sortOption=ASC

### API GET POST With Search | PUBLIC API

GET http://localhost:8000/posts?searchPostTitle=sakura

### API GET POST WITH SORT AND PAGINATION

GET http://localhost:8000/posts?sortOption=ASC&pageNumber=1

### API GET POST WITH SEARCH AND SORT

GET http://localhost:8000/posts?searchPostTitle=sakura&sortOption=ASC

### API GET POST WITH SEARCH , PAGINATE AND SORT

GET http://localhost:8000/posts?searchPostTitle=naruto&sortOption=ASC&pageNumber=1

### API GET POST BY WRITER 
GET http://localhost:8000/posts?writerId=1

### API GET POST BY WRITER AND PAGE NUMBER
GET http://localhost:8000/posts?writerId=15&pageNumber=1

### API GET POST BY WRITER AND SORT | PUBLIC API

GET http://localhost:8000/posts??writerId=15&sortOption=ASC

### API GET POST BY WRITER ,SORT AND SEARCH | PUBLIC API

GET http://localhost:8000/posts?writerId=15&searchPostTitle=sakura

### API GET POST BY WRITER ,SORT, PAGINATE

GET http://localhost:8000/posts?writerId=1&sortOption=ASC&pageNumber=1

### API GET POST BY WRITER ,SORT AND SEARCH

GET http://localhost:8000/posts?writerId=15&searchPostTitle=sakura&sortOption=ASC

### API GET POST  BY WRITER ,SORT, PAGINATE AND SEARCH

GET http://localhost:8000/posts?writerId=15&searchPostTitle=naruto&sortOption=ASC&pageNumber=1


### API GET ONE POST | PUBLIC API
GET http://localhost:8000/posts/11

### API EDIT POST | PRIVATE API, MEMERLUKAN TOKEN UNTUK MENGAKSESNYA
PUT  http://localhost:8000/posts/77
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsImZ1bGxuYW1lIjoiZ3JlaXEiLCJlbWFpbCI6ImdyZWlxYmFydUBnbWFpbC5jb20iLCJpYXQiOjE2NjA1NTc2NzAsImV4cCI6MTY2MDY0NDA3MH0.ISUqlaOzPNuowGc8hgyyOHBYYryigVLWrU7ozIHibts

{
    "title": "Update Pantai Gatra 10",
    "image": "https://salsawisata.b-cdn.net/wp-content/uploads/2021/11/Pantai-Gatra.jpg",
    "body": "Pantai Gatra merupakan salah satu pantai terindah di Indonesia"
}

### API EDIT USER | PRIVATE API, MEMERLUKAN TOKEN UNTUK MENGAKSESNYA
PUT  http://localhost:8000/user/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsImZ1bGxuYW1lIjoiZ3JlaXEiLCJlbWFpbCI6ImdyZWlxYmFydUBnbWFpbC5jb20iLCJpYXQiOjE2NjA1NTc2NzAsImV4cCI6MTY2MDY0NDA3MH0.ISUqlaOzPNuowGc8hgyyOHBYYryigVLWrU7ozIHibts

{
    "fullname" : "greiq2",
    "email" : "lala@gmail.com",
    "password" : "123456@12Aa"
}