

### API SWAGGER

GET http://localhost:8000/api-docs

### API CREATE A NEW USER | JIKA EMAIL SUDAH TERDAFTAR SEBELUMNYA, MAKA PENDAFTARAN GAGAL

### KET : PASSWORD AKAN DI AMANKAN DALAM BENTUK BCRYPT 

POST http://localhost:8000/user/registration
Content-Type: application/json

{
    "fullname": "greiq",
    "email": "greq3@gmail.com",
    "password": "123456&Qz"
}


### API LOGIN, KET : MENDAPATKAN TOKEN BARU SETIAP KALI LOGIN LAGI
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "email": "greq@gmail.com",
    "password": "123456&Qz"
}

### API CREATE A NEW POST - 

### KET : JIKA INI PRIVATE API, KITA PERLU MEMASUKAN TOKEN YG TADI SUDAH KAMU DAPATKAN SAAT LOGIN, IBARAT TANDA PENGENAL

POST http://localhost:8000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImZ1bGxuYW1lIjoiZ3JlaXEyIiwiZW1haWwiOiJncmVpcTJAZ21haWwuY29tIiwiaWF0IjoxNjYwMjg0ODYwLCJleHAiOjE2NjAzNzEyNjB9.-RZEsgWhTIVwOQgcGS1sw8kw1vGP_6YgzXNPWXWwMLE

{
    "title": "Pantai Gatra greiq 2",
    "image": "https://salsawisata.b-cdn.net/wp-content/uploads/2021/11/Pantai-Gatra.jpg",
    "body": "Pantai Gatra merupakan salah satu pantai terindah di Indonesia"
}

### API GET ALL USER | PUBLIC API (EXAMPLE)

GET http://localhost:8000/users

### API GET ALL POST| PUBLIC API

GET http://localhost:8000/posts

### API GET POST WITH PAGINATE

GET http://localhost:8000/posts?pageNumber=1

### API GET POST SORT | PUBLIC API

GET http://localhost:8000/posts?sortOption=ASC

### API GET POST With Search | PUBLIC API

GET http://localhost:8000/posts?searchPostTitle=sakura

### API GET POST WITH PAGINATE

GET http://localhost:8000/posts?sortOption=ASC&pageNumber=1

### API GET POST WITH PAGINATE

GET http://localhost:8000/posts?searchPostTitle=sakura&sortOption=ASC

### API GET POST WITH PAGINATE

GET http://localhost:8000/posts?searchPostTitle=naruto&sortOption=ASC&pageNumber=1

### API GET POST ByWRITER | PUBLIC API

GET http://localhost:8000/posts?writerId=15&searchPostTitle=sakura

### API GET POST ByWRITER | PUBLIC API

GET http://localhost:8000/posts?writerId=15&searchPostTitle=sakura&pageNumber=1


### API GET ONE POST | PUBLIC API
GET http://localhost:8000/posts/11

### API EDIT POST | PRIVATE API, MEMERLUKAN TOKEN UNTUK MENGAKSESNYA
PUT  http://localhost:8000/posts/0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiZnVsbG5hbWUiOiJncmVpcSBiYXJ1IiwiZW1haWwiOiJncmVpcXp6ekBnbWFpbC5jb20iLCJpYXQiOjE2NjAyODMxNDQsImV4cCI6MTY2MDM2OTU0NH0.R-nkuuJKTPEGsbVQldUxNdfit_H3YGvES_fDfw8mc50

{
    "title": "Update Pantai Gatra 10",
    "image": "https://salsawisata.b-cdn.net/wp-content/uploads/2021/11/Pantai-Gatra.jpg",
    "body": "Pantai Gatra merupakan salah satu pantai terindah di Indonesia"
}

### API EDIT USER | PRIVATE API, MEMERLUKAN TOKEN UNTUK MENGAKSESNYA
PUT  http://localhost:8000/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjgsImZ1bGxuYW1lIjoiZ3JlaXEiLCJlbWFpbCI6ImdyZXFAZ21haWwuY29tIiwiaWF0IjoxNjYwMzAyOTIwLCJleHAiOjE2NjAzODkzMjB9.uZQj1OYHF2Iwlq7QbonrIem-Vv2rf3Mb1IPGIBzc7S8

{
    "fullname" : "greiq2",
    "email" : "bbzzb1111bbzzbbbzzzzqqacccc@gmail.com",
    "password" : "123456@12A"
}