

### API CREATE A NEW USER | JIKA EMAIL SUDAH TERDAFTAR SEBELUMNYA, MAKA PENDAFTARAN GAGAL

### KET : PASSWORD AKAN DI AMANKAN DALAM BENTUK BCRYPT 

POST http://localhost:8000/user/registration
Content-Type: application/json

{
    "fullname": "greiq4",
    "email": "greiq4@gmail.com",
    "password": "12345678"
}


### API LOGIN, KET : MENDAPATKAN TOKEN BARU SETIAP KALI LOGIN LAGI
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "email": "greiq4@gmail.com",
    "password": "12345678"
}

### API CREATE A NEW POST - 

### KET : JIKA INI PRIVATE API, KITA PERLU MEMASUKAN TOKEN YG TADI SUDAH KAMU DAPATKAN SAAT LOGIN, IBARAT TANDA PENGENAL

POST http://localhost:8000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZnVsbG5hbWUiOiJncmVpcTQiLCJlbWFpbCI6ImdyZWlxNEBnbWFpbC5jb20iLCJpYXQiOjE2NTk4ODkxNzYsImV4cCI6MTY1OTk3NTU3Nn0.F3SrKD3yqiggrq03WQCGshQhmT8K_JnnYYG8i6O6P10

{
    "title": "Pantai Gatra",
    "image": "https://salsawisata.b-cdn.net/wp-content/uploads/2021/11/Pantai-Gatra.jpg",
    "body": "Pantai Gatra merupakan salah satu pantai terindah di Indonesia"
}

### API GET ALL USER | PUBLIC API

GET http://localhost:8000/users

### API GET ALL POST/ByWRITER | PUBLIC API

GET http://localhost:8000/posts?writer=4

### API GET ONE POST | PUBLIC API
GET http://localhost:8000/posts/7

### API EDIT POST | PRIVATE API, MEMERLUKAN TOKEN UNTUK MENGAKSESNYA
PUT  http://localhost:8000/posts/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZnVsbG5hbWUiOiJncmVpcTQiLCJlbWFpbCI6ImdyZWlxNEBnbWFpbC5jb20iLCJpYXQiOjE2NTk4ODkxNzYsImV4cCI6MTY1OTk3NTU3Nn0.F3SrKD3yqiggrq03WQCGshQhmT8K_JnnYYG8i6O6P10

{
    "title": "Update Pantai Gatra",
    "image": "https://salsawisata.b-cdn.net/wp-content/uploads/2021/11/Pantai-Gatra.jpg",
    "body": "Pantai Gatra merupakan salah satu pantai terindah di Indonesia"
}

### API EDIT USER | PRIVATE API, MEMERLUKAN TOKEN UNTUK MENGAKSESNYA
PUT  http://localhost:8000/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZnVsbG5hbWUiOiJncmVpcTQiLCJlbWFpbCI6ImdyZWlxNEBnbWFpbC5jb20iLCJpYXQiOjE2NTk4ODkxNzYsImV4cCI6MTY1OTk3NTU3Nn0.F3SrKD3yqiggrq03WQCGshQhmT8K_JnnYYG8i6O6P10

{
    "fullname" : "greiq2",
    "email" : "greiq2@gmail.com",
    "password" : "123456"
}